language: node_js
node_js:
  - "stable"
notifications:
  email: false

cache:
  directories:
  - node_modules

script:
  npm run build

deploy:
  provider: pages
  api_key:
    secure: wtw
  skip_cleanup: true
  github-token: wtw
  local_dir: build
  on:
    branch: master
