const MAX_COUNT_GENRES = 9;
const GENRE_DEFAULT = `All genres`;

const START_SHOWN_MOVIES_AMOUNT = 8;
const SHOW_MOVIES_ON_CLICK = 8;

const TabName = {
  OVERVIEW: `Overview`,
  DETAILS: `Details`,
  REVIEWS: `Reviews`,
};

export {MAX_COUNT_GENRES, GENRE_DEFAULT, TabName, START_SHOWN_MOVIES_AMOUNT, SHOW_MOVIES_ON_CLICK};
