const promoFilm = {
  "name": `Snatch`,
  "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
  "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
  "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
  "background_color": `#FDFDFC`,
  "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
  "rating": 0.2,
  "scores_count": 716577,
  "director": `Guy Ritchie`,
  "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
  "run_time": 104,
  "genre": `Comedy`,
  "released": 2000,
  "id": 1,
  "is_favorite": false,
  "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
  "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
};

const films = [
  {
    "name": `Snatch`,
    "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
    "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
    "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
    "background_color": `#FDFDFC`,
    "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
    "rating": 0.2,
    "scores_count": 716577,
    "director": `Guy Ritchie`,
    "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
    "run_time": 104,
    "genre": `Comedy`,
    "released": 2000,
    "id": 1,
    "is_favorite": false,
    "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    "name": `Snatch`,
    "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
    "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
    "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
    "background_color": `#FDFDFC`,
    "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
    "rating": 0.2,
    "scores_count": 716577,
    "director": `Guy Ritchie`,
    "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
    "run_time": 104,
    "genre": `Comedy`,
    "released": 2000,
    "id": 2,
    "is_favorite": false,
    "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    "name": `Snatch`,
    "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
    "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
    "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
    "background_color": `#FDFDFC`,
    "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
    "rating": 0.2,
    "scores_count": 716577,
    "director": `Guy Ritchie`,
    "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
    "run_time": 104,
    "genre": `Comedy`,
    "released": 2000,
    "id": 3,
    "is_favorite": false,
    "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    "name": `Snatch`,
    "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
    "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
    "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
    "background_color": `#FDFDFC`,
    "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
    "rating": 0.2,
    "scores_count": 716577,
    "director": `Guy Ritchie`,
    "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
    "run_time": 104,
    "genre": `Comedy`,
    "released": 2000,
    "id": 4,
    "is_favorite": false,
    "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  },
  {
    "name": `Snatch`,
    "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
    "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
    "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
    "background_color": `#FDFDFC`,
    "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
    "rating": 0.2,
    "scores_count": 716577,
    "director": `Guy Ritchie`,
    "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
    "run_time": 104,
    "genre": `Comedy`,
    "released": 2000,
    "id": 5,
    "is_favorite": false,
    "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
    "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
  }
];

const film = {
  "name": `Snatch`,
  "poster_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/poster/Snatch.jpg`,
  "preview_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/preview/snatch.jpg`,
  "background_image": `https://htmlacademy-react-3.appspot.com/wtw/static/film/background/Snatch.jpg`,
  "background_color": `#FDFDFC`,
  "description": `Unscrupulous boxing promoters, violent bookmakers, a Russian gangster, incompetent amateur robbers and supposedly Jewish jewelers fight to track down a priceless stolen diamond.`,
  "rating": 0.2,
  "scores_count": 716577,
  "director": `Guy Ritchie`,
  "starring": [`Jason Statham`, `Brad Pitt`, `Benicio Del Toro`],
  "run_time": 104,
  "genre": `Comedy`,
  "released": 2000,
  "id": 1,
  "is_favorite": false,
  "video_link": `http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4`,
  "preview_video_link": `https://upload.wikimedia.org/wikipedia/commons/transcoded/b/b3/Big_Buck_Bunny_Trailer_400p.ogv/Big_Buck_Bunny_Trailer_400p.ogv.360p.webm`,
};

export {promoFilm, films, film};
